services:
  postgres:
    image: postgres:15
    container_name: progresso-ai
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: progressoai
    ports:
      - "5433:5432" # Changed the host port to 5433
    volumes:
      - progresso-ai:/var/lib/postgresql/data

volumes:
  progresso-ai:
